# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ website ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    env:
      MODE: production
      
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Setup NodeJS
      - name: Set up Node.js
        uses: actions/setup-node@v1
      - name: Initialize
        run: npm i
        
      # Build
      - name: Build
        run: ./build.sh
      - name: Clean
        run: |
          rm -rf node_modules
          rm -rf src
              
      # Package
      - name: Upload Site        
        uses: actions/upload-artifact@v2.2.4
        with:
          name: lachee.dev
          
      
